<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add a comment...' => '',
    'Click here to cancel reply.' => '',
    'Comment' => '',
    'Comment cannot be blank.' => '',
    'Comment has been deleted.' => '',
    'Comment has been saved.' => '',
    'Comment has not been deleted. Please try again!' => '',
    'Comments' => '',
    'Comments Management' => '',
    'Content' => '',
    'Created by' => '',
    'Created date' => '',
    'Delete' => '',
    'Entity' => '',
    'Entity ID' => '',
    'Go Back' => '',
    'ID' => '',
    'Level' => '',
    'Oops, something went wrong. Please try again later.' => '',
    'Parent ID' => '',
    'Related to' => '',
    'Reply' => '',
    'Select Author' => '',
    'Select Status' => '',
    'Status' => '',
    'The "entityIdAttribute" value for widget model cannot be empty.' => '',
    'The "model" property must be set.' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Comment: {0}' => '',
    'Updated by' => '',
    'Updated date' => '',
];
