<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Denied.' => '',
    'Add comment' => '',
    'Author avatar' => '',
    'Cancel' => '',
    'Comment author' => '',
    'Comment not found.' => '',
    'Comment was deleted.' => '',
    'Comments' => '',
    'Created at' => '',
    'Created by' => '',
    'Delete' => '',
    'Edit' => '',
    'Entity' => '',
    'ID' => '',
    'Post comment' => '',
    'Reply' => '',
    'Text' => '',
    'Unknown author' => '',
    'Updated at' => '',
    'Updated at {date-relative}' => '',
    'Updated by' => '',
    'Your name' => '',
];
