<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API access token' => '',
    'Email' => '',
    'Expire At' => '',
    'Not Active' => '',
    'Password' => '',
    'Roles' => '',
    'Token' => '',
    '"{attribute}" must be a valid JSON' => '"{attribute}" должен содержать валидный JSON',
    'Active' => 'Активно',
    'Article ID' => 'ID Статьи',
    'Article View' => 'Шаблон статьи',
    'Author' => 'Автор',
    'Base URL' => 'Базовый URL',
    'Base Url' => 'Базовый Url',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID карусели',
    'Category' => 'Категория',
    'Comment' => 'Комментарий',
    'Component' => 'Компонент',
    'Config' => 'Настройки',
    'Created At' => 'Создано',
    'Created at' => 'Создано',
    'Deleted' => 'Удалено',
    'Down to maintenance.' => 'Закрыто на обслуживание',
    'E-mail' => 'E-mail',
    'File Type' => 'Тип файла',
    'First name' => 'Имя',
    'Gender' => 'Пол',
    'ID' => 'ID',
    'Image' => 'Изображение',
    'Key' => 'Ключ',
    'Last login' => 'Последний вход',
    'Last name' => 'Фамилия',
    'Locale' => 'Локаль',
    'Middle name (if you have)' => 'Отчество',
    'Name' => 'Имя',
    'Order' => 'Порядок',
    'Page View' => 'Шаблон страницы',
    'Parent Category' => 'Родительская категория',
    'Path' => 'Путь',
    'Profile picture' => 'Аватар',
    'Published' => 'Опубликовано',
    'Published At' => 'Дата публикации',
    'Size' => 'Размер',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'Thumbnail' => 'Эскиз изображения',
    'Title' => 'Название',
    'Type' => 'Тип',
    'Updated At' => 'Обновлено',
    'Updated at' => 'Последнее обновление',
    'Updater' => 'Обновивщий',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'ID пользователя',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',
    'Mapala.net sweeping the planet and inviting you to join. The project will be released soon. Hurry up!'=>'Mapala.net шагает по планете и приглашает вас присоединиться. Проект будет в ближайшее время. Поторопись!',
    'Mapala.net invite you to join the worldwide community' => 'Mapala.net приглашает тебя присоединиться к глобальному сообществу',
    'Keep passwords securely. We can not restore it.' =>'Сохраняйте пароль НАДЕЖНО. Мы не можем его восстановить.',
  
    
];
